AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - cfn-nag-service/private_key.rb

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 23

Style/StderrPuts:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/ClassLength:
  Max: 115

Lint/IneffectiveAccessModifier:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Style/RaiseArgs:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Lint/UnusedMethodArgument:
  Exclude:
    - cfn-nag-lambda/handler.rb

Lint/UselessAssignment:
  Enabled: false