version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - sam deploy --stack-name cfn-nag-service --template-file packaged-template.yaml --capabilities CAPABILITY_IAM
artifacts:
    files:
      - '**/*'
