version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      ruby: 2.5
  pre_build:
    commands:
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - bundle install
      - ruby tests/unit/test_handler.rb
  build:
    commands:
      - sam build
      - sam package --template-file .aws-sam/build/template.yaml     --s3-bucket stelligent-cfn-nag-service --output-template-file packaged-template.yaml
artifacts:
    files:
      - '**/*'
