version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - sam build
      - sam package --template-file .aws-sam/build/template.yaml     --s3-bucket stelligent-cfn-nag-service --output-template-file packaged-template.yaml
artifacts:
    files:
      - '**/*'
