AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for cfn-nag

Globals:
  Function:
    Timeout: 3

Resources:
  CfnNagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./cfn_nag
      Handler: handler.LambdaFunctions::Handler.process
      Runtime: ruby2.5
      Layers:
        - !Ref LibSodiumLayer
      Policies:
       - Version: '2012-10-17'
         Statement:
           - Effect: Allow
             Action:
               - ssm:GetParameter
             Resource: '*'
      Events:
        Scan:
          Type: Api
          Properties:
            Path: /scan
            Method: post
        ScanSecure:
          Type: Api
          Properties:
            Path: /scan_secure
            Method: post
        Status:
          Type: Api
          Properties:
            Path: /status
            Method: GET
  LibSodiumLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - ruby2.5
      Content:
        S3Bucket: stelligent-cfn-nag-service
        S3Key: libsodium.zip
      Description: Libsodium shared objects
      LayerName: libsodium

Outputs:
  CfnNagApi:
    Description: "API Gateway endpoint URL for Prod stage for CFN Nag function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scan/"
  CfnNagFunction:
    Description: "CFN Nag Lambda Function ARN"
    Value: !GetAtt CfnNagFunction.Arn
  CfnNagFunctionIamRole:
    Description: "Implicit IAM Role created for CfnNag function"
    Value: !GetAtt CfnNagFunctionRole.Arn
