AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: cfn-nag service running lambda behind API GW

Globals:
  Function:
    Timeout: 3

Parameters:
  S3Bucket:
    Type: String
  SsmPathForKey:
    Type: String
    Default: '/CfnNagService/signing_key'

Resources:
  CfnNagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: cfn-nag-lambda/handler.Handler.process
      Runtime: ruby2.5
      Layers:
        - !Ref LibSodiumLayer
      Environment:
        Variables:
          private_key_ssm_path: !Ref SsmPathForKey
      Policies:
       - Version: '2012-10-17'
         Statement:
           - Effect: Allow
             Action:
               - ssm:GetParameter
             Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SsmPathForKey}'
      Events:
        Scan:
          Type: Api
          Properties:
            Path: /scan
            Method: post
        ScanSecure:
          Type: Api
          Properties:
            Path: /signed_scan
            Method: post
        Status:
          Type: Api
          Properties:
            Path: /status
            Method: GET
  LibSodiumLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - ruby2.5
      Content:
        S3Bucket: !Ref 'S3Bucket'
        S3Key: libsodium.zip
      Description: Libsodium shared objects
      LayerName: libsodium

Outputs:
  CfnNagApi:
    Description: "API Gateway endpoint URL for Prod stage for CFN Nag function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scan/"
  CfnNagFunction:
    Description: "CFN Nag Lambda Function ARN"
    Value: !GetAtt CfnNagFunction.Arn
  CfnNagFunctionIamRole:
    Description: "Implicit IAM Role created for CfnNag function"
    Value: !GetAtt CfnNagFunctionRole.Arn
