version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      ruby: 2.6
      docker: 18
  pre_build:
    commands:
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - bundle install
      - apt-get install -y libsodium-dev
      - ruby tests/unit/test_handler.rb
  build:
    commands:
      - ./scripts/extract_libsodium.sh
      - sam build --use-container
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket $S3_BUCKET_NAME --output-template-file packaged-template.yaml
artifacts:
    files:
      - '**/*'
